### ISSUE TITLE
Headphones that without analog converter or DAC will not work

### ISSUE THREAD

**Issue by uwu-gl** [OnePlus12R-development/android_device_oneplus_aston#1]
Hi there!
Thanks for your developing! 
Recently I am running your PixelOS build and updated to June release. I found a question that the USB-C device can't working, such as wired headphones. And I catched some logcat here:

The logcat when my headphones are plugged in:
![Screenshot_20240710-225934](https://github.com/OnePlus12R-development/android_device_oneplus_aston/assets/137363994/9157312f-cd3d-465d-935d-c896f17a698e)

Remove headphones:
![Screenshot_20240710-230017](https://github.com/OnePlus12R-development/android_device_oneplus_aston/assets/137363994/6f395999-f8f2-4450-9130-4b6312272ae4)

I am looking for your reply. Thanks!

**Comment by uwu-gl** [comment]
By the way, I am using CN version (OnePlus Ace 3)

**Comment by inferno0230** [comment]
@uwu-gl does your 3.5mm to typeC adaptor has digital to analog converter?
If not, it won't work

**Comment by Venkat3620** [comment]
@uwu-gl Nuke fune whun?

**Comment by uwu-gl** [comment]
> @uwu-gl does your 3.5mm to typeC adaptor has digital to analog converter? If not, it won't work

Sorry, my headphone is type-C directly.
The earphones have a type-c interface and are directly connected to the phone. They work fine on other phones.

**Comment by inferno0230** [comment]
> > @uwu-gl does your 3.5mm to typeC adaptor has digital to analog converter? If not, it won't work
> 
> Sorry, my headphone is type-C directly.

It has to have a dac in it, else it won't work on custom rom. I use wired earphones and they work fine

**Comment by uwu-gl** [comment]
> > > @uwu-gl does your 3.5mm to typeC adaptor has digital to analog converter? If not, it won't work
> > 
> > 
> > Sorry, my headphone is type-C directly.
> 
> It has to have a dac in it, else it won't work on custom rom. I use wired earphones and they work fine

Ok, thanks!
